version: "3.3"

services:

  mariadb-service:
    container_name: mariadb-service
    hostname: mariadb-service
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bOSesGIQxahs9SP1@A7rj1dzWJmtHZ59qQoyZvWG
      MYSQL_USER: rocktrade
      MYSQL_PASSWORD: E2rH9Pj5YiaN1CrPcTYH
      TZ: "America/Sao_Paulo"
